name: Renovate Tokens

on:
  schedule:
    - cron: "* * * * *"
  push:
    branches:
      - 'main'

jobs:
  repositories:
    name: Renovate Tokens
    runs-on: ubuntu-latest
    steps:
      - name: Generate App Token for Renovate
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: app-token
        with:
          app-id: ${{ secrets.RENOVATE_BOT_CLIENT_ID }}
          private-key: ${{ secrets.RENOVATE_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ secrets.RENOVATE_REPOSITORIES }}
      - name: List repositories
        shell: bash
        run: |
          gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /installation/repositories
#  set-token-for-repository:
#    name: Renovate Tokens
#    runs-on: ubuntu-latest
#    steps:
#      - name: Generate App Token for Renovate to be shared across repos
#        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
#        id: shared-token
#        with:
#          app-id: ${{ secrets.RENOVATE_BOT_CLIENT_ID }}
#          private-key: ${{ secrets.RENOVATE_BOT_PRIVATE_KEY }}
#          owner: ${{ github.repository_owner }}
#          repositories:
#            - ${{ github.repository }}
