name: Renovate Tokens

on:
  schedule:
    - cron: "* * * * *"
  push:
    branches:
      - 'main'

jobs:
  repositories:
    name: Renovate Tokens
    runs-on: ubuntu-latest
    outputs:
      repositories: ${{ steps.repositories.outputs.result }}
    steps:
      - name: Generate App Token for Renovate
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: app-token
        with:
          app-id: ${{ secrets.RENOVATE_BOT_CLIENT_ID }}
          private-key: ${{ secrets.RENOVATE_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ secrets.RENOVATE_REPOSITORIES }}
      - name: List repositories
        uses: actions/github-script@v8
        id: repositories
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const response = await octokit.request('GET /installation/repositories', {
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            });
            return response.data.repositories.flatMap((repo) => repo.name);
  set-token-for-repository:
    name: Renovate Tokens
    runs-on: ubuntu-latest
    needs:
      - repositories
    strategy:
      fail-fast: false
      matrix:
        repository: ${{ fromJSON(needs.repositories.outputs.repositories) }}
    steps:
      - run: echo "${{ matrix.repository }}"
      - name: Generate App Token for Renovate to be shared across repos
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: shared-token
        with:
          app-id: ${{ secrets.RENOVATE_BOT_CLIENT_ID }}
          private-key: ${{ secrets.RENOVATE_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ matrix.repository }}
      - name: Set WorkFlow Dispatch Token
        uses: actions/github-script@v8
        id: repositories
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            await octokit.request('PUT /repos/{owner}/{repo}/actions/secrets/{secret_name}', {
              owner: '${{ github.repository_owner }}',
              repo: '${{ matrix.repository }}',
              secret_name: 'RENOVATE_WORKFLOW_DISPATCH_TOKEN',
              value: '${{ steps.app-token.outputs.token }}',
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            });